name: Bug Report
description: Problems with CCStopper?
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        > ⚠ We are aware that the Credit Card Prompt patch may not be working for some people. Please check that 1) the entry is in Windows Firewall, 2) no antivirus/other firewall is interfering with Windows Firewall.
        
        > If the issue presists, please go [here](https://github.com/eaaasun/CCStopper/issues/42) and provide us your region/country. We suspect it's because of a regional patch from Adobe.
        
        Thanks for taking the time to fill out this bug report! 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please include as much detail as possible.
      placeholder: "CCStopper caused the heat death of the universe because it didn't block an Adobe server that sent a death ray to my house!"
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result?
      placeholder: "Closes Adobe's background processes."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version?
      description: To make things as frictionless as possible, plesae copy the exact release tag [here](https://github.com/eaaasun/CCStopper/releases).
      placeholder: "v2.8.12_pre.2"
    validations:
      required: true
  - type: input
    id: windows-ver
    attributes:
      label: Windows Version?
      description: Which Windows version(s) are you experiencing this bug in? Development/testing are done in Windows 10, so other versions may not work.
      placeholder: "Windows 10 21H1"
    validations:
      required: true
